// This file is generated by the reader program.

#include <iostream>
#include <stdlib.h>
#include <fstream>
using namespace std;
int main(int argc, char** argv)
{
if (argc == 2){
	double entree[2];
	int i = 0;
	ifstream file(argv[1], ios::in);
	if(file){
	/* Reading the point */
		while ( !file.eof()) file >> entree[i++];
		file.close();
		ofstream fic("input.txt", ios::trunc);
		fic.precision(15);
		for (i = 0; i < 2; ++i){
		fic << entree[i] << " ";}
		fic.close();system("HS23/truth.exe");
		cout << endl;
		system("HS23/cons1.exe");
		cout << endl;
		system("HS23/cons2.exe");
		cout << endl;
		system("HS23/cons3.exe");
		cout << endl;
		}
	}
	else{
		cout << "Error." << endl;
		return 1;}

	return 0;
}
